-- MySQL Script generated by MySQL Workbench
-- Sun Dec 26 23:46:31 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema storeDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema storeDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `storeDB` DEFAULT CHARACTER SET utf8 ;
USE `storeDB` ;

-- -----------------------------------------------------
-- Table `storeDB`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storeDB`.`category` (
  `id_category` INT NOT NULL AUTO_INCREMENT,
  `Typename` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_category`),
  UNIQUE INDEX `Typename_UNIQUE` (`Typename` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `storeDB`.`brands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storeDB`.`brands` (
  `id_brand` INT NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id_brand`),
  UNIQUE INDEX `brend_UNIQUE` (`brand` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `storeDB`.`brand_product_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storeDB`.`brand_product_types` (
  `id_brand_product_types` INT NOT NULL,
  `id_brand` INT NOT NULL,
  `id_category` INT NOT NULL,
  PRIMARY KEY (`id_brand_product_types`),
  INDEX `fk_product_types_brand_id_idx` (`id_brand` ASC) VISIBLE,
  INDEX `fk_product_types_category_id_idx` (`id_category` ASC) VISIBLE,
  CONSTRAINT `fk_product_types_brand_id`
    FOREIGN KEY (`id_brand`)
    REFERENCES `storeDB`.`brands` (`id_brand`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_product_types_category_id`
    FOREIGN KEY (`id_category`)
    REFERENCES `storeDB`.`category` (`id_category`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `storeDB`.`worktops`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storeDB`.`worktops` (
  `id_worktops` INT NOT NULL AUTO_INCREMENT,
  `f_id_category` INT NULL,
  `f_id_brand` INT NULL,
  `name` VARCHAR(60) NULL,
  `decor` VARCHAR(20) NULL,
  `texture` VARCHAR(10) NULL,
  `workedge` VARCHAR(20) NULL,
  `mesure_unit` VARCHAR(10) NULL,
  `length` INT NULL,
  `width` INT NULL,
  `thickness` INT NULL,
  `picture` VARCHAR(60) NULL,
  `cost` DECIMAL(10,4) NULL,
  PRIMARY KEY (`id_worktops`),
  INDEX `fk_worktops_brands_idx` (`f_id_brand` ASC) VISIBLE,
  INDEX `fk_worktops_category_idx` (`f_id_category` ASC) VISIBLE,
  CONSTRAINT `fk_worktops_category`
    FOREIGN KEY (`f_id_category`)
    REFERENCES `storeDB`.`brand_product_types` (`id_category`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_worktops_brands`
    FOREIGN KEY (`f_id_brand`)
    REFERENCES `storeDB`.`brand_product_types` (`id_brand`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
