-- MySQL Script generated by MySQL Workbench
-- Sun Jan  2 21:53:45 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema storeDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema storeDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `storeDB` DEFAULT CHARACTER SET utf8 ;
USE `storeDB` ;

-- -----------------------------------------------------
-- Table `storeDB`.`brands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storeDB`.`brands` (
  `id_brand` INT NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_brand`),
  UNIQUE INDEX `brand_UNIQUE` (`brand` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `storeDB`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storeDB`.`categories` (
  `id_category` INT NOT NULL AUTO_INCREMENT,
  `Category` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_category`),
  UNIQUE INDEX `Category_UNIQUE` (`Category` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `storeDB`.`formats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storeDB`.`formats` (
  `id_format` INT NOT NULL AUTO_INCREMENT,
  `length` INT NOT NULL,
  `width` INT NOT NULL,
  PRIMARY KEY (`id_format`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `storeDB`.`thickness`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storeDB`.`thickness` (
  `id_thickness` INT NOT NULL AUTO_INCREMENT,
  `thickness` DECIMAL(10,1) NOT NULL,
  PRIMARY KEY (`id_thickness`),
  UNIQUE INDEX `thickness_UNIQUE` (`thickness` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `storeDB`.`decors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storeDB`.`decors` (
  `id_decor` INT NOT NULL AUTO_INCREMENT,
  `decor_article` VARCHAR(45) NULL,
  `decor_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id_decor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `storeDB`.`textures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storeDB`.`textures` (
  `id_texture` INT NOT NULL AUTO_INCREMENT,
  `Texture` VARCHAR(45) NULL,
  PRIMARY KEY (`id_texture`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `storeDB`.`materials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storeDB`.`materials` (
  `id_materials` INT NOT NULL AUTO_INCREMENT,
  `f_id_brand` INT NOT NULL,
  `f_id_category` INT NOT NULL,
  `f_id_format` INT NOT NULL,
  `f_id_thickness` INT NOT NULL,
  `f_id_decor` INT NOT NULL,
  `f_id_texture` INT NOT NULL,
  `measure_unit` VARCHAR(5) NULL,
  `cost` DECIMAL(10,4) NULL,
  `picture_address` VARCHAR(100) NULL,
  PRIMARY KEY (`id_materials`),
  INDEX `fk_material_brand_idx` (`f_id_brand` ASC) VISIBLE,
  INDEX `fk_Materials_Categories1_idx` (`f_id_category` ASC) VISIBLE,
  INDEX `fk_Materials_Format1_idx` (`f_id_format` ASC) VISIBLE,
  INDEX `fk_Materials_Thickness1_idx` (`f_id_thickness` ASC) VISIBLE,
  INDEX `fk_Materials_decors1_idx` (`f_id_decor` ASC) VISIBLE,
  INDEX `fk_Materials_Textures1_idx` (`f_id_texture` ASC) VISIBLE,
  CONSTRAINT `fk_material_brand`
    FOREIGN KEY (`f_id_brand`)
    REFERENCES `storeDB`.`brands` (`id_brand`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Materials_Categories1`
    FOREIGN KEY (`f_id_category`)
    REFERENCES `storeDB`.`categories` (`id_category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Materials_Format1`
    FOREIGN KEY (`f_id_format`)
    REFERENCES `storeDB`.`formats` (`id_format`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Materials_Thickness1`
    FOREIGN KEY (`f_id_thickness`)
    REFERENCES `storeDB`.`thickness` (`id_thickness`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Materials_decors1`
    FOREIGN KEY (`f_id_decor`)
    REFERENCES `storeDB`.`decors` (`id_decor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Materials_Textures1`
    FOREIGN KEY (`f_id_texture`)
    REFERENCES `storeDB`.`textures` (`id_texture`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
